apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtimeops-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: realtimeops
  template:
    metadata:
      labels:
        app: realtimeops
    spec:
      containers:
      - name: realtimeops
        image: vishal108/realtimeops:latest
        ports:
        - containerPort: 3030
        readinessProbe:
          httpGet:
            path: /
            port: 3030
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: realtimeops-svc
spec:
  type: LoadBalancer
  selector:
    app: realtimeops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030

